<a href="https://colab.research.google.com/github/sirivellamadhu/sirivellamadhu.github.io/blob/master/reduce10digitsto5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow  as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
(x_train, y_train) ,(x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [47]:
for i in range(20):
  print(y_train[i])

5
0
4
1
9
2
1
3
1
4
3
5
3
6
1
7
2
8
6
9


In [0]:
#0as4 1as7 2as5  3as8 6as9

y_train = np.where(y_train==6,  4,  y_train)
y_train = np.where(y_train==7,  1,  y_train)
y_train = np.where(y_train==5,  2,  y_train)
y_train = np.where(y_train==8,  3,  y_train)
y_train = np.where(y_train==9,  0,  y_train)

In [0]:
#0as4 1as7 2as5  3as8 6as9

y_test = np.where(y_test==6,  4,  y_test)
y_test = np.where(y_test==7,  1,  y_test)
y_test = np.where(y_test==5,  2,  y_test)
y_test = np.where(y_test==8,  3,  y_test)
y_test = np.where(y_test==9,  0,  y_test)


In [50]:
for i in range(20):
  print(y_train[i])

1
2
1
0
4
1
4
0
2
0
0
4
0
0
1
2
0
1
3
4


In [0]:
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)

In [0]:
input_shape = (28, 28, 1)

In [0]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255

In [0]:
# Importing the required Keras modules containing model and layers
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D
# Creating a Sequential Model and adding the layers
model = Sequential()
model.add(Conv2D(28, kernel_size=(3,3), input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten()) # Flattening the 2D arrays for fully connected layers
model.add(Dense(128, activation=tf.nn.relu))
model.add(Dropout(0.2))
model.add(Dense(5,activation=tf.nn.softmax))

In [55]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])
model.fit(x=x_train,y=y_train, epochs=10)

Epoch 1/10
60000/60000 [==============================] - 38s 635us/step - loss: 0.1885 - acc: 0.9377
Epoch 2/10
60000/60000 [==============================] - 37s 621us/step - loss: 0.0844 - acc: 0.9733
Epoch 3/10
60000/60000 [==============================] - 37s 616us/step - loss: 0.0599 - acc: 0.9804
Epoch 4/10
60000/60000 [==============================] - 37s 613us/step - loss: 0.0469 - acc: 0.9848
Epoch 5/10
60000/60000 [==============================] - 37s 619us/step - loss: 0.0376 - acc: 0.9878
Epoch 6/10
60000/60000 [==============================] - 37s 618us/step - loss: 0.0306 - acc: 0.9891
Epoch 7/10
60000/60000 [==============================] - 37s 620us/step - loss: 0.0277 - acc: 0.9904
Epoch 8/10
60000/60000 [==============================] - 37s 623us/step - loss: 0.0231 - acc: 0.9918
Epoch 9/10
60000/60000 [==============================] - 37s 620us/step - loss: 0.0207 - acc: 0.9931
Epoch 10/10
60000/60000 [==============================] - 37s 625us/step - loss: 

In [56]:
model.evaluate(x_test, y_test)


10000/10000 [==============================] - 2s 166us/step


[0.061150615554935575, 0.9832]

In [0]:
test_predictions = model.predict_classes(x_test)

In [59]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_true = y_test, y_pred = test_predictions)
print(cm)


[[1964    7    8    4    6]
 [   5 2142   11    3    2]
 [   6   12 1889   13    4]
 [   9    7   25 1939    4]
 [  21    6   11    4 1898]]
